use std::fs;

use anyhow::{Context, Result};

use super::validate::checked_hex;
use crate::paths::{alacritty_colors_path, alacritty_config_path};

pub const ALACRITTY_IMPORT_LINE: &str = "import = [\"~/.config/alacritty/atmosphere-colors.toml\"]";

/// Returns Ok(false) when Alacritty is not installed (whole step skipped).
pub fn ensure_alacritty_colors(
    background: &str,
    foreground: &str,
    accent: &str,
    on_accent: &str,
    surface: &str,
) -> Result<bool> {
    if which_alacritty().is_none() {
        return Ok(false);
    }
    let background = checked_hex(background, "background")?;
    let foreground = checked_hex(foreground, "foreground")?;
    let accent = checked_hex(accent, "accent")?;
    let on_accent = checked_hex(on_accent, "on accent")?;
    let surface = checked_hex(surface, "surface")?;

    // Minimal mapping: terminal background/foreground + cursor/selection from
    // the theme palette. Alacritty reads this file only via the import below.
    let body = render_colors(&background, &foreground, &accent, &on_accent, &surface);
    let colors_path = alacritty_colors_path();
    if let Some(parent) = colors_path.parent() {
        fs::create_dir_all(parent)?;
    }
    super::atomic::atomic_write(&colors_path, &body)?;
    ensure_import()?;
    Ok(true)
}

/// Pure render of `atmosphere-colors.toml` (unit-testable; no fs).
fn render_colors(
    background: &str,
    foreground: &str,
    accent: &str,
    on_accent: &str,
    surface: &str,
) -> String {
    format!(
        "# Generated by Atmosphere; do not edit.\n\
[colors.primary]\n\
background = \"{background}\"\n\
foreground = \"{foreground}\"\n\
[colors.cursor]\n\
text = \"{on_accent}\"\n\
cursor = \"{accent}\"\n\
[colors.selection]\n\
text = \"{on_accent}\"\n\
background = \"{accent}\"\n\
[colors.normal]\n\
black = \"{background}\"\n\
white = \"{foreground}\"\n\
blue = \"{accent}\"\n\
cyan = \"{surface}\"\n",
    )
}

fn which_alacritty() -> Option<std::path::PathBuf> {
    std::env::var_os("PATH").and_then(|paths| {
        std::env::split_paths(&paths)
            .map(|dir| dir.join("alacritty"))
            .find(|p| p.is_file())
    })
}

fn ensure_import() -> Result<()> {
    let cfg = alacritty_config_path();
    if let Some(parent) = cfg.parent() {
        fs::create_dir_all(parent)?;
    }
    if !cfg.is_file() {
        super::atomic::atomic_write(
            &cfg,
            &format!("live_config_reload = true\n{ALACRITTY_IMPORT_LINE}\n"),
        )?;
        return Ok(());
    }
    let existing = fs::read_to_string(&cfg).with_context(|| format!("read {}", cfg.display()))?;
    let merged = merge_import(&existing);
    if merged != existing {
        super::atomic::atomic_write(&cfg, &merged)?;
    }
    Ok(())
}

/// Pure import merge (unit-testable): adds `live_config_reload` and the
/// import line only when absent; returns the input unchanged otherwise, so
/// user content is never rewritten.
fn merge_import(existing: &str) -> String {
    if existing.contains("atmosphere-colors.toml") {
        return existing.to_string();
    }
    let mut merged = existing.to_string();
    if !merged.ends_with('\n') {
        merged.push('\n');
    }
    if !merged.contains("live_config_reload") {
        merged.push_str("live_config_reload = true\n");
    }
    merged.push_str(ALACRITTY_IMPORT_LINE);
    merged.push('\n');
    merged
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn render_carries_palette_and_no_legacy_path() {
        let body = render_colors("#111111", "#eeeeee", "#112233", "#ffffff", "#222222");
        for hex in ["#111111", "#eeeeee", "#112233", "#ffffff", "#222222"] {
            assert!(body.contains(hex), "missing {hex}");
        }
        assert!(body.contains("[colors.primary]"));
        assert!(!body.contains("colors.toml"), "legacy path must not appear");
    }

    #[test]
    fn merge_is_idempotent_and_minimal() {
        let created = merge_import("");
        assert!(created.contains("live_config_reload = true"));
        assert!(created.contains(ALACRITTY_IMPORT_LINE));

        // Present import: byte-identical, user content untouched.
        let user =
            "font:\n  size: 12.0\nimport = [\"~/.config/alacritty/atmosphere-colors.toml\"]\n";
        assert_eq!(merge_import(user), user);

        // Missing pieces appended without touching the rest.
        let merged = merge_import("font:\n  size: 12.0\n");
        assert!(merged.starts_with("font:\n  size: 12.0\n"));
        assert!(merged.contains("live_config_reload = true"));
        assert!(merged.contains(ALACRITTY_IMPORT_LINE));
        // Second merge is a fixed point.
        assert_eq!(merge_import(&merged), merged);
    }
}
