use std::path::PathBuf;

use anyhow::Result;
use gio::Settings;
use gio::prelude::*;

use super::atomic::atomic_write;
use super::glass::shell_glass_block;
use super::model::{ColorMode, GlassSettings, Palette};
use crate::paths::shell_theme_css_path;

pub fn yaru_import_path(mode: ColorMode) -> PathBuf {
    match mode {
        ColorMode::Dark => PathBuf::from("/usr/share/gnome-shell/theme/Yaru-dark/gnome-shell.css"),
        ColorMode::Light => PathBuf::from("/usr/share/gnome-shell/theme/Yaru/gnome-shell.css"),
    }
}

pub fn write_shell_css(mode: ColorMode, palette: &Palette, glass: &GlassSettings) -> Result<()> {
    let import = yaru_import_path(mode);
    let import_line = if import.is_file() {
        format!("@import url('file://{}');\n", import.display())
    } else {
        let fallback = PathBuf::from("/usr/share/gnome-shell/theme/gnome-shell.css");
        if fallback.is_file() {
            format!("@import url('file://{}');\n", fallback.display())
        } else {
            String::new()
        }
    };

    let block = shell_glass_block(palette, glass);
    let css = format!(
        "/* Generated by Atmosphere */\n{import}{block}",
        import = import_line,
        block = block
    );

    let path = shell_theme_css_path();
    atomic_write(&path, &css)
}

pub fn reload_user_theme() -> Result<()> {
    let settings = Settings::new("org.gnome.shell.extensions.user-theme");
    settings.set_string("name", "")?;
    settings.set_string("name", "Atmosphere")?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn yaru_paths_follow_mode() {
        assert_eq!(
            yaru_import_path(ColorMode::Dark),
            std::path::PathBuf::from("/usr/share/gnome-shell/theme/Yaru-dark/gnome-shell.css")
        );
        assert_eq!(
            yaru_import_path(ColorMode::Light),
            std::path::PathBuf::from("/usr/share/gnome-shell/theme/Yaru/gnome-shell.css")
        );
    }
}
